"$schema" = 'https://starship.rs/config-schema.json'
add_newline = false

# format = "$all"

format = """
$hostname\
$localip\
$directory\
$nodejs\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$git_user\
$docker_context\
$env_var\
$custom\
$sudo\
$line_break\
$battery\
$time\
$status\
$shell\
$character\
"""

# format = """
# [┌───────────────────>](bold green)
# [│](bold green)$directory$rust$package
# [└─>](bold green) """


[[battery.display]]
threshold = 20
style = "bold red"


[directory]
truncate_to_repo = false

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"

# [time]
# disabled = false


[git_branch]
# style = "bg:cyan fg:green"
symbol = ""
format = "[$symbol$branch(:$remote_branch)]($style) "

[nodejs]
format = "[$symbol($version )]($style)"

# [shell]
# disabled = false

[username]
format = "[$user@]($style)"
disabled = false
show_always = true

[custom.git_user]
command="git config user.name"
detect_folders = [".git"]
format = "[(\\($output\\) )]($style)"
style = "dimmed yellow"
